### PR TITLE
Add methods to check if a connection is valid (not closed or in stale state)

### PR DESCRIPTION
**Pull request by bluemontag**
This PR only adds 2 methods for checking if a connection is active, that is, open and accepting queries ("alive")

The 2 methods are:

* ZConnection#isAlive(timeout: Int) : This version checks if a connection is active using the corresponding "isAlive()" method in the java.sql.Connection interface.
* ZConnection#isAlive(): Uses a validation query in a PreparedStatement to check if the connection is still active.

### CODE REVIEW

**Review by jdegoes — APPROVED** [review]

**Comment by jdegoes** [comment]
@bluemontag Good to merge when the build passes! Be sure to format the code properly and check that all tests pass. 🙏

**Comment by bluemontag** [comment]
I am away from home now, if it can wait until tonight, I will correct it
when I get home.

Thanks!!    🙏🙏🙏
Ignacio

**Comment by bluemontag** [comment]
Hi @jdegoes , I have formatted the ZConnection class again using the file .scalafmt.conf in the project, I hope now the file passes the checks.

**Comment by jdegoes** [comment]
@bluemontag Great, thank you. Just waiting to see if the CI passes!

**Comment by bluemontag** [comment]
@jdegoes there is a failing test, but I think it does not have something to do with this PR:

insert - sql - ZConnectionPoolSpec
        Exception in thread "zio-fiber-51" org.h2.jdbc.JdbcSQLSyntaxErrorException: org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "USERS" already exists; SQL statement:
        
              create table users (
                id identity primary key,
                name varchar not null,
                age int not null
         [[42](https://github.com/zio/zio-jdbc/runs/6623409694?check_suite_focus=true#step:5:43)101-210]
        	at zio.jdbc.ZConnection.access(ZConnection.scala:29)

**Comment by jdegoes** [comment]
Trying to re-run now.

**Comment by bluemontag** [comment]
Thank you @jdegoes !! :-) I have updated my fork also !

**Comment by jdegoes** [comment]
Thank you for your contribution!

**Pull request merged**
