### PR TITLE
Use PreparedStatement.closeOnCompletion

### PR DESCRIPTION
**Pull request by domartynov**
I've noticed we don't close `ResultSet` and `PreparedStatement`, adding the `closeOnCompletion` call should help. It's probably supported by most modern drivers, but I've checked only with Postgres driver. 

TODOs:
- [ ] add closing for `selectStream` as it does not guarantee reading to completion
- [ ] add tests

Or maybe just add explicit closes. For `selectStream`, we probably want to use a bounded queue and to have one `attemptBlocking` to loop pushing new items with closes in the finally block -- for Postgres, the driver seems to implement adaptive fetch, so `next` calls can be too cheap to iterate via a stream even on the same fiber, and it's hard to use a fixed chunk size 🤔

### CODE REVIEW

**Review by jdegoes — APPROVED** [review]

**Comment by jdegoes** [comment]
We should probably modify:

```scala
  private[jdbc] def executeSqlWith[A](sql: Sql[_])(f: PreparedStatement => A): ZIO[Any, Throwable, A]
```

to:

```scala
  private[jdbc] def executeSqlWith[A](sql: Sql[_])(f: PreparedStatement => A): ZIO[Scope, Throwable, A]
```

Then we can close via `ZIO.addFinalizer` inside the execution method, and we can roll that `Scope` up, into the use of a connection from the connection pool (i.e. release when we return the connection to the pool).

**Comment by karvanit** [comment]
After running into "Too many open cursors", I tried adding the `closeOnCompletion` and the code was still failing.
I have added code that also closes the ResultSets and then it passed. It is in my own fork of [zio-jdbc](https://github.com/karvanit/zio-jdbc/tree/early-closing) but I don't understand enough to create proper test cases and such to submit a pull request.

**Comment by jdegoes** [comment]
@karvanit Do you need help here?

**Comment by karvanit** [comment]
I am now using zio-jdbc 0.0.2 and the new code works like a charm. I think this is because we now eagerly close the statements as early as possible.
So I no longer have code that can test this change.

**Pull request closed without merging**
