### PR TITLE
add valuesBatched() function call

### PR DESCRIPTION
**Pull request by kyh24**

### CODE REVIEW

**Comment by jdegoes** [comment]
@kyh24 Thank you, can you please run `scalafmt` to format the code so that the CI build will pass? Then I will be happy to merge this! 🙏

**Comment by kyh24** [comment]
hey @jdegoes , I believe I ran it and CI is passing??

**Comment by kyh24** [comment]
Actually @jdegoes I'm seeing the linter still fail, but I ran scalafmt and it shows success with nothing to commit. Would you be able to help me with this?

**Comment by jdegoes** [comment]
Thank you!

**Pull request merged**
